[settings]
experimental = true
disable_hints = ["*"]

[tools]
# do not update version of python/node/ruby for installed global tool bin
python = "3.11.9"
rust   = "1.82.0"
node   = "22.9.0"
ruby   = "3.3.5"
go     = "1.23.3"
deno   = "latest"
bun    = "latest"
lua    = "latest"
zig    = "latest"
usage  = "latest"
