[source.crates-io]
replace-with = 'ustc'
registry = "https://github.com/rust-lang/crates.io-index"

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

[source.rustcc]
registry = "git://crates.rustcc.cn/crates.io-index"
